name: 🚀 Deploy FastAPI to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🔑 Connect to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu
            if [ ! -d "connectjew-crawler-service" ]; then
              git clone https://github.com/${{ github.repository }}.git
            fi
            cd connectjew-crawler-service
            git pull origin main
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

            sudo fuser -k 8000/tcp || true
            nohup venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 &
